version: '3.8'
services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - appnet

  mysql:
    image: mysql:8
    container_name: prueba_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: michael
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  nginx:
    image: nginx:stable-alpine
    container_name: prueba_nginx
    depends_on:
      - app
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

    networks:
      - appnet

networks:
  appnet:

volumes:
  mysql_data: