# docker-compose.frontend.yaml
services:
  # Producción - Servicio con Nginx
  vue_prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    profiles: ["production"]

  # Desarrollo - Servicio con hot-reload
  vue_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    profiles: ["development"]