FROM node:20-alpine AS build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY . .

# Build directo sin TypeScript
RUN npx vite build

FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
